### ISSUE TITLE
Meta issue: Release PyF 1.0.0.0

### ISSUE THREAD

**Issue by guibou** [guibou/PyF#63]
With the removal of `haskell-src-ext` (see #61), `PyF` will soon be able to be the best formatting library ever!

More seriously, on reddit, when I announced the release of `PyF`, I received (negative) comments on the following points:

- Too much dependencies. This is fixed by #61 and soon #8. The only remaining deps is `uniplate`, it may be possible to kill it with a manual traversal of the GHC expression AST.
- Template Haskell. There is no fix for that now unfortunately. We may work on #49, but plugin does not provides "multiline" support, so that's not perfect either.
- No whitespace stripping.

I propose that we focus on a release fo PyF 1.0 with, on a technical point:

- [x] merged #61 
- [x] a merged solution of #8. In progress, see #64
- [x] (Optional) no `uniplate`. Replaced by `syb` which does have less dependencies.
- [x] Whitespace trimming. #62.
- [ ] More robust `Meta.hs`. At least it should handle all expressions.
- [ ] (Optional) Released `Meta.hs` as a new library.
- [x] #37 and similar, a way to add more `Integral`-like types to PyF.

- [ ] On a non technical point, I'd like PyF 1.0.0.0 to be really good for the user experience. A cleaning of the `Readme.md` page. Right now, there is too much things. I'd like most of the examples to move in haddock (and be tested with doctest) so users will be able to see the examples directly in hackage. I'd like also good haddock and perhaps a renaming of the `Class` things in order to get a really nice API.

**Comment by guibou** [comment]
Every important ticket are closed. I now need to:

- Clean/ documentation. Perhaps #4
- See what I'll do with `Meta.hs`.

**Comment by guibou** [comment]
I think PyF 0.10.0.0 was released and it cover everything listed here. That's not version 1.0.0.0, but that's great ;)
